name: Go 1.15
on: {push: {branches: [feature/go1.15]}, pull_request: {branches: [feature/go1.15]}}
jobs: {test: {runs-on: ubuntu-latest, steps: [{uses: actions/checkout@v7}, {run: go -C go1.15 test .}]}}
