name: Go 1.14
on: {push: {branches: [feature/go1.14]}, pull_request: {branches: [feature/go1.14]}}
jobs: {test: {runs-on: ubuntu-latest, steps: [{uses: actions/checkout@v7}, {run: go -C go1.14 test .}]}}
