name: Go 1.16
on: {push: {branches: [feature/go1.16]}, pull_request: {branches: [feature/go1.16]}}
jobs: {test: {runs-on: ubuntu-latest, steps: [{uses: actions/checkout@v7}, {run: go -C go1.16 test .}]}}
