name: Go 1.17
on: {push: {branches: [feature/go1.17]}, pull_request: {branches: [feature/go1.17]}}
jobs: {test: {runs-on: ubuntu-latest, steps: [{uses: actions/checkout@v7}, {run: go -C go1.17 test .}]}}
